name: model-2-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy>=1.26.0
  - pip:
      - azureml-defaults
      - torch>=2.0.0
      - torchvision
      - transformers>=4.44.0
      - safetensors>=0.4.3
      - Pillow>=10.0.0
      - opencv-python-headless>=4.8.0
      - inference-schema

